name: znn_address_generator
description: generates infinite addresses
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  args: ^2.4.2
  console_bars: ^1.2.0
  dcli: ^3.2.1
  synchronized: ^3.1.0
  znn_sdk_dart:
    git:
      url: https://github.com/zenon-network/znn_sdk_dart.git
      ref: master
